version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootPassXXX
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=myAdmin
      - ME_CONFIG_BASICAUTH_PASSWORD=myPassword

volumes:
  data: {}

networks:
  default:
    name: mongodb_network